### PR TITLE
Make hardcoded variables configurable from content repo

### LINKED ISSUE #70: Hard coded configuration variables
The following variables are hard coded in some places in the code, while they should be configured in the config.json file in the content repository:

- [ ] Github organization in the banner GH logo link
- [ ] Github repository in the banner GH logo link
- [ ] Organization logo in the banner (currently eScience Center)
- [ ] Organization website in the banner (currently eScience Center)
- [ ] ~~reveal.js theme (currently the eScience theme)~~
- [ ] footer organization name and link

### PR DESCRIPTION
**Pull request by JaroCamphuijsen**
- [x] Github organization in the banner GH logo link
- [x] Github repository in the banner GH logo link
- [x] Organization logo in the banner (currently eScience Center)
- [x] Organization website in the banner (currently eScience Center)
- [ ] ~~reveal.js theme (currently the eScience theme)~~
- [x] footer organization name and link

fixes #70

### CODE REVIEW

**Comment by JaroCamphuijsen** [comment]
Content repositories should also change because of this PR. The following changes are needed:

- [ ] Expand config.json with organization url
- [ ] Add organization logo image to content repository
- [ ] Expand config.json with logo image location

**Review by raar1 — APPROVED** [review]
Nice, good work. These are useful things to be able to configure!

**Comment by raar1** [comment]
Also glad not to see "Let's Stay in Touch!" 400 times a day

**Comment by raar1** [comment]
Actually, be careful after merging to check that the equations render correctly (since this branch does not have that functionality yet)

**Comment by JaroCamphuijsen** [comment]
> Actually, be careful after merging to check that the equations render correctly (since this branch does not have that functionality yet)

Yeah I merged it in here and checked whether it still works. Thanks!

**Comment by JaroCamphuijsen** [comment]
> Actually, be careful after merging to check that the equations render correctly (since this branch does not have that functionality yet)

Yeah I merged it in here and checked whether it still works. Thanks!

**Pull request merged**
